server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: ServerPatrol
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    # check-process-definitions: false  #这个比较重要，不配置的话会扫描类路径下的processes下的.xml文件
  master:
    datasource:    #数据库连接信息
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 1234abcd
      filters: stat,wall,slf4j
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 6000
      maxPoolPreparedStatementPerConnectionSize: 20
      minEvictableIdleTimeMillis: 30000
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      useGlobalDataSourceStat: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: select 'x'
  activiti-db:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/qhsp_activiti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 1234abcd
      filters: stat,wall,slf4j
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 6000
      maxPoolPreparedStatementPerConnectionSize: 20
      minEvictableIdleTimeMillis: 30000
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      useGlobalDataSourceStat: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: select 'x'
  jackieonway:
    swagger:
      enable: true
      api-info:
        version: 1.0
        title: "请假接口信息"
        description: "请假Swagger接口信息"
        terms-of-service-url: "http://${spring.cloud.client.ip-address}:${server.port}"
        contact:
          name: "jackieonway"
          url: "http://${spring.cloud.client.ip-address}:${server.port}"
        params:
          - name: "AccessToken"
            description: "登录校验Token"
            model-ref:
              type: "string"
            param-type: "header"
            required: false
            value: 63232
activiti:
  root:
    path: D:\\activiti\\
logging:
  level:
    com.github.jackieonway: debug